### ISSUE TITLE
Missing Paramater Password at Build Time

### ISSUE THREAD

**Issue by joelrozen** [vvo/next-iron-session#377]
Hi Team,

I am having issues building my next app inside a docker file with iron session.

I have created a wrapper function around withIronSession so I can use with api or getServerSideProps without having to duplicate all the withIronSession options everytime I use it.

```typescript
export type NextIronRequest = NextApiRequest & { session: Session }
export type NextIronServerSideProps =
  | GetServerSidePropsContext & { req: NextIronRequest }

export const secureEndpoint = (handler) =>
  withIronSession(handler, {
    password: process.env.SESSION_SECRET,
    cookieName: 'secure_session',
    cookieOptions: {
      secure: process.env.NODE_ENV === 'production',
      sameSite: true,
      expires: dayjs().add(1, 'day').toDate(),
    },
  })
```

Use case as so:
```typescript
export const getServerSideProps = secureEndpoint(
  async (ctx: NextIronServerSideProps) => {
    const user = ctx.req.session?.get('user')

    if (!user) {
      return {
        redirect: {
          destination: '/login',
        },
      }
    }

    return { props: { user } }
  }
)
```

- OR -

```typescript
const handler = async (req: NextIronRequest, res: NextApiResponse) => {
  if (!req.session?.get('user')) {
    res.status(401)
    return res.send('Unauthorised')
  }

  if (req.method === 'POST') return ADD_NEW_BOOKING(req, res)
  if (req.method === 'GET') return GET_BOOKINGS(req, res)

  res.status(404)
  return res.send('')
}

export default secureEndpoint(handler)
```

It's working perfectly in dev, I can run `npm run build` no issues as well, but as soon as I try to run `npm run build` inside a Docker container for deployment, I am hitting the error:
```
#12 30.83 Error: next-iron-session: Missing parameter `password`
#12 30.83     at throwOnNoPassword (/app/node_modules/next-iron-session/dist/index.js:26:9)
#12 30.83     at withIronSession (/app/node_modules/next-iron-session/dist/index.js:107:14)
#12 30.83     at secureEndpoint (/app/.next/server/pages/login.js:78:97)
#12 30.83     at Module.1368 (/app/.next/server/pages/login.js:41:104)
#12 30.83     at __webpack_require__ (/app/.next/server/webpack-runtime.js:25:43)
#12 30.83     at __webpack_exec__ (/app/.next/server/pages/login.js:143:52)
#12 30.83     at /app/.next/server/pages/login.js:144:79
#12 30.83     at Function.__webpack_require__.X (/app/.next/server/webpack-runtime.js:108:21)
#12 30.83     at /app/.next/server/pages/login.js:144:47
#12 30.83     at Object.<anonymous> (/app/.next/server/pages/login.js:147:3) {
#12 30.83   type: 'Error'
#12 30.83 }
```

It appears to me that the build script is trying to interpolate the process.env at build time instead of run time, because if I hard code in the password it builds fine inside docker.

Any ideas why this would be happening? Or has anyone successfully deployed inside a docker container without having to pass the password as an ARG / ENV inside the Dockerfile? README clearly says 'The password is a private key you must pass at **runtime**' 

TIA

**Comment by vvo** [comment]
Hey @joelrozen I believe this is more of a Next.js generic question on how to ensure env variables are only filled at runtime rather than at builtime.

If you remove next-iron-session form the question you'll have the same issue. By default Next.js will try to replace all process.env.* variables when you run npm run build.

I agree that the README of this lib is misleading on this question though.

Could you check how to NOT replace env variables at build time and only at runtime using Next.js? We don't do anything particular in the lib on that matter.

Thanks!

**Comment by joelrozen** [comment]
@vvo I don't believe this is a generic next.js question, as I have built tens of docker images of nextjs projects all of which contain env vars (that don't exist at build time) without issue.

The compiled code in dist also still references process.env.* anyway, as it should. I believe in this case therre might be a prebuild script happening somewhere that is attempting to run iron-session and iron-session is throwing the error. I have managed a temporary solution as follows: 

```
export const secureEndpoint = (handler) =>
  withIronSession(handler, {
    password: process.env.SESSION_SECRET || 'a',
    cookieName: 'secure_session',
    cookieOptions: {
      secure: process.env.NODE_ENV === 'production',
      sameSite: true,
      expires: dayjs().add(1, 'day').toDate(),
    },
  })
```

Which when built comes out exactly the same, so in prod it will still reference the SESSION_SECRET instead of 'a' but this isn't an ideal solution imo.

**Comment by vvo** [comment]
Hey @joelrozen thanks for digging this in. There's no prebuild script or anything that could trigger this behavior in the source code of next-iron-session.

While counterintuitive, I believe this is the current normal behavior of Next.js.

This issue might be one where you could read/ask for more details: https://github.com/vercel/next.js/issues/22266

And also from their docs
![image](https://user-images.githubusercontent.com/123822/126133972-4b178321-07c5-44e2-b669-439bf92cd75a.png)

https://nextjs.org/docs/basic-features/environment-variables

The way we use next iron session might be the issue here, when we do "export const getServerSideProps = secureEndpoint(" then at build time for a page Next.js will try to run this code (even if not included in the static build, since this is not part of the static page). This is why you're seeing this error and I would love to learn more if you jump in the linked Next.js issue.

Thanks!

**Comment by aphofstede** [comment]
As I understand it, `export const getServerSideProps = withIronSession(...)` **needs** to be evaluated at build time because `getServerSideProps` needs to be assigned a value when loading that module. The callback is never actually called during pre-rendering afaik and the password is not actually required to set up the handler.
Would it make sense to move the password requirement to run-time? (Instead of in the function argument destructuring as it is now)

**Comment by sicarius97** [comment]
@vvo I agree with @aphofstede and @joelrozen that this is indeed a next-iron-session issue, as I use multiple other empty env variables that don't get evaluated at build time, and this does cause an issue with docker. I have not run into this issue besides with this library, and I think what @aphofstede would probably be an ideal solution

**Comment by aphofstede** [comment]
What I meant in my earlier comment was to remove the `throwOnNoPassword()` checks and do them inside the callback instead. (which would cause those checks to only run at run-time)

Something like:
```
export function withIronSession(
  withIronSessionWrapperHandler,
  {
    ttl = 15 * 24 * 3600,
    cookieName,
    password,
    cookieOptions = {},
  },
) {
  return async function withIronSessionHandler(...args) {
    const handlerType = args[0] && args[1] ? "api" : "ssr";
    const req = handlerType === "api" ? args[0] : args[0].req;
    const res = handlerType === "api" ? args[1] : args[0].res;

    const options = {
      ttl,
      cookieName: cookieName || throwOnNoCookieName(),
      password: password || throwOnNoPassword(),
      cookieOptions
    }
    await applySession(req, res, options);
...
```
If an alternate API would work better with typescript we could get behind that, though I think this issue mainly comes from the withIronSession() callback pattern. When defining server side props statically I think one could already do something along these lines:
```
export const getServerSideProps = async ({req, res}) => {
    const session = await applySession(req, res, { cookieName, password });
    ...
}
```

**Comment by vvo** [comment]
Hey there, I believe the new version (v6) now does what you expect, you can check it here: https://github.com/vvo/iron-session/releases/tag/v6.0.0

**Comment by Sionesevaki** [comment]
I also ran into this issue, I renamed my .env file from .env.development to .env and fixed the issue. Leaving this here incase it a fix for anyone
